export const POST_COHORTE = "POST_COHORTE";
export const DEL_COHORTE = "DEL_COHORTE";
export const GET_COHORTES = "GET_COHORTES";
export const PUT_COHORTES = "PUT_COHORTES";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const GET_ACTIVE_COHORTES = "GET_ACTIVE_COHORTES";
export const GET_COHORTE = "GET_COHORTE";
export const PUT_INSTRUCTOR = "PUT_INSTRUCTOR";
