export const POST_USER = "POST_USER";
export const DEL_USER = "DEL_USER";
export const GET_USERS = "GET_USERS";
export const PUT_USERS = "PUT_USERS";
export const SEND_INVITATION = "SEND_INVITATION";
export const GET_STUDENTS = "GET_STUDENTS";
export const GET_USERS_BY_COHORTE = "GET_USERS_BY_COHORTE";
export const ERROR_MESSAGE = "ERROR_MESSAGE"
export const GET_USER_BY_TOKEN = "GET_USER_BY_TOKEN"
export const DELETE_USER_COHORTE = "DELETE_USER_COHORTE"
export const MIGRAR_USER_COHORTE = "MIGRAR_USER_COHORTE"
export const USERS_GROUP = "USERS_GROUP"
export const SEARCH_BY_NAME = "SEARCH_BY_NAME"
export const GET_USER_EDIT = "GET_USER_EDIT"
export const UPDATE_USER_PASSWORD = " UPDATE_USER_PASSWORD,"
export const PUT_NOTAS = "PUT_NOTAS";

