export const POST_USER = "POST_USER";
export const DEL_USER = "DEL_USER";
export const GET_USERS = "GET_USERS";
export const PUT_USERS = "PUT_USERS";
export const GET_USERS_BY_COHORTE = "GET_USERS_BY_COHORTE";
export const ERROR_MESSAGE = "ERROR_MESSAGE"
export const DELETE_USER_COHORTE = "DELETE_USER_COHORTE"
export const MIGRAR_USER_COHORTE = "MIGRAR_USER_COHORTE"